allprojects { project ->
  def artifactoryUsername = System.getenv("ARTIFACTORY_USERNAME")
  def artifactoryPassword = System.getenv("ARTIFACTORY_PASSWORD")
  if (artifactoryUsername && artifactoryPassword) {
    repositories {
      maven {
        name = 'spring-commercial-release'
        url = 'https://usw1.packages.broadcom.com/spring-enterprise-maven-prod-local'
        credentials {
          username = artifactoryUsername
          password = artifactoryPassword
        }
      }
      if (project.version.toString().endsWith('-SNAPSHOT')) {
        maven {
          name = 'spring-commercial-snapshot'
          url = 'https://usw1.packages.broadcom.com/spring-enterprise-maven-dev-local'
          credentials {
            username = artifactoryUsername
            password = artifactoryPassword
          }
        }
      }
    }
  }
}
