version: 2

updates:
  - package-ecosystem: gradle
    target-branch: 1.0.x
    directory: /
    milestone: 21 # 1.0.x
    schedule:
      interval: weekly
    labels:
      - 'type: dependency-upgrade'

  - package-ecosystem: github-actions
    target-branch: 1.0.x
    directory: /
    milestone: 21 # 1.0.x
    schedule:
      interval: weekly
    labels:
      - 'type: dependency-upgrade'
