name: Send Notification
description: Sends a Google Chat message as a notification of the job's outcome

inputs:
  webhook-url:
    description: 'Google Chat Webhook URL'
    required: true

runs:
  using: composite
  steps:
    - id: run-info
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKFLOW_REF: ${{ github.workflow_ref }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_EVENT_SENDER_LOGIN: ${{ github.event.sender.login }}
        GITHUB_EVENT_SENDER_HTML_URL: ${{ github.event.sender.html_url }}
        GITHUB_EVENT_PULL_REQUEST_HTML_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_EVENT_HEAD_COMMIT_URL: ${{ github.event.head_commit.url }}
      run: |
        # Pull additional details from GitHub API
        json=$(gh run view "$GITHUB_RUN_ID" -R "$GITHUB_REPOSITORY" --json name,number,displayTitle,url,headSha,jobs)
        # Get sanitized display title (usually a commit message or PR title) from GitHub API
        displayTitle=$(echo $json | jq -r .displayTitle | sed 's/"/\\"/g')
        # Parse workflow yaml file name from full ref name
        workflow=$(echo "$GITHUB_WORKFLOW_REF" | awk -F'/|@' '{ print $5 }')
        # Build workflow URL with branch name
        workflowUrl="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/workflows/${workflow}?query=branch%3A${GITHUB_REF_NAME}"
        # Get workflow name from GitHub API (also available as "github.workflow")
        workflowName=$(echo $json | jq -r .name | sed 's/"/\\"/g')
        # Get workflow run URL from GitHub API
        runUrl=$(echo $json | jq -r .url)
        # Get workflow run number from GitHub API (also available as "github.run_number")
        runNumber=$(echo $json | jq -r .number)
        # Determine overall run status (based on all jobs preceding this one)
        runStatus=$(echo $json | jq -r '.jobs | map(select(.conclusion != "")) | if all(.conclusion == "success" or .conclusion == "skipped") then "succeeded" elif any(.conclusion == "failure") then "failed" elif any(.conclusion == "cancelled") then "cancelled" else "unsuccessful" end')
        # **** Templates ****
        # Workflow status with link to workflow run
        workflowStatus="<${runUrl}|${displayTitle}> ${runStatus}"
        # Workflow info with link to all workflow runs for this branch
        workflowInfo="<${workflowUrl}|${workflowName}> #${runNumber}"
        # Determine run info, with either pull request, commit or manual run info
        if [ ! -z "${GITHUB_EVENT_SENDER_LOGIN}" ] ; then
          author="${GITHUB_EVENT_SENDER_LOGIN}"
          authorUrl="${GITHUB_EVENT_SENDER_HTML_URL}"
          if [ ! -z "${GITHUB_EVENT_PULL_REQUEST_HTML_URL}" ] ; then
            prNumber="${GITHUB_EVENT_PULL_REQUEST_NUMBER}"
            prUrl="${GITHUB_EVENT_PULL_REQUEST_HTML_URL}"
            runInfo="Pull request #<${prUrl}|${prNumber}> opened by <${authorUrl}|${author}>"
          elif [ ! -z "${GITHUB_EVENT_HEAD_COMMIT_URL}" ] ; then
            commitUrl="${GITHUB_EVENT_HEAD_COMMIT_URL}"
            shaId=$(echo $json | jq -r .headSha | awk '{ print substr($0, 0, 7) }')
            runInfo="Commit <${commitUrl}|${shaId}> pushed by <${authorUrl}|${author}>"
          else
            runInfo="Manually run by <${authorUrl}|${author}>"
          fi
        else
          runInfo="Run via scheduled workflow"
        fi
        # Build job info messages, joined in single line (multiline breaks GITHUB_ENV)
        jobInfo=$(echo $json | jq -r '.jobs | map(select(.conclusion != "")) | map("* <" + .url + "|" + .name + "> was " + .conclusion) | join("\\n")')
        # Set results as env vars
        echo "WORKFLOW_STATUS=$workflowStatus" >> $GITHUB_ENV
        echo "WORKFLOW_INFO=$workflowInfo" >> $GITHUB_ENV
        echo "RUN_INFO=$runInfo" >> $GITHUB_ENV
        echo "JOB_INFO=$jobInfo" >> $GITHUB_ENV
        # Output status
        echo "result=$runStatus" >> $GITHUB_OUTPUT
    - shell: bash
      if: ${{ contains(fromJSON('["failed", "cancelled", "unsuccessful"]'), steps.run-info.outputs.result) }}
      run: |
        curl -X POST "$WEBHOOK_URL" -H 'Content-Type: application/json' -d "{ \"text\": \"${WORKFLOW_STATUS}\n${WORKFLOW_INFO}: ${RUN_INFO}\n\n${JOB_INFO}\" }" || true
      env:
        WEBHOOK_URL: ${{ inputs.webhook-url }}
