= Spring Security Maven Plugin

Spring Security Maven Plugin is a Gradle plugin that provides tasks for publishing releases to Maven Central (Sonatype) and Spring (Artifactory) repositories.

To use the plugin, apply the plugin in your project's root `build.gradle` and in each sub-module that requires publishing artifacts:

[source,gradle]
----
plugins {
	id "io.spring.security.maven" version "1.0.4"
}
----

== Overview
This plugin has two main goals:

1. Automatically apply plugins and configuration for publishing artifacts to both Maven Central (Sonatype) and Spring (Artifactory).
2. Provide tasks for automatically choosing which artifact repository to publish artifacts to based on the project version.

This plugin performs the following on each sub-module it is applied to:

* Applies the `maven-publish` plugin
* Applies the `signing` plugin
* Applies the `com.jfrog.artifactory` plugin
* Creates a `mavenJava` publication with the `java` component
* Configures the `signing` extension using gradle properties
* Configures the `publishing` extension to sign artifacts
* Creates a `local` repository for publishing artifacts to a local directory
* Configures the `artifactory` extension using gradle properties

== Task Reference

== `artifactoryPublish`

This task is provided by the `com.jfrog.artifactory` plugin, and can be used directly to publish artifacts (including releases) to Artifactory.

*Example:*

[source,bash]
----
export ORG_GRADLE_PROJECT_signingKey=...
export ORG_GRADLE_PROJECT_signingPassword=...
ARTIFACTORY_USERNAME=...
ARTIFACTORY_PASSWORD=...
./gradlew artifactoryPublish -PartifactoryUsername="$ARTIFACTORY_USERNAME" -PartifactoryPassword="$ARTIFACTORY_PASSWORD" --stacktrace
----

== `publishToMavenLocal`

This task is provided by the `maven-publish` plugin, and can be used directly to publish artifacts to the local Maven cache for testing.

*Example:*

[source,bash]
----
./gradlew publishToMavenLocal
----

== `publishMavenJavaPublicationToLocalRepository`

This task is provided by the `maven-publish` plugin when the `local` repository is defined, and can be used directly to publish artifacts to a local directory (`build/publication/repos`) for testing.

*Example:*

[source,bash]
----
./gradlew publishMavenJavaPublicationToLocalRepository
----
