name: Build Pull Request

on:
  workflow_call:
    inputs:
      java-version:
        description: Version of the JDK to use to run the Gradle command.
        required: false
        default: '17'
        type: string
      distribution:
        description: Distribution of the JDK to use to run the Gradle command.
        required: false
        default: 'temurin'
        type: string
      runs-on:
        description: GitHub Actions runner to run the build task on.
        required: false
        default: 'ubuntu-latest'
        type: string
    secrets:
      COMMERCIAL_ARTIFACTORY_USERNAME:
        required: false
      COMMERCIAL_ARTIFACTORY_PASSWORD:
        required: false
      DEVELOCITY_ACCESS_KEY:
        required: false

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: spring-io/spring-security-release-tools
          ref: ${{ github.action_ref }}
          path: _srt
          fetch-depth: 1
      - uses: ./_srt/.github/actions/run-gradle
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          artifactory-username: ${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}
          artifactory-password: ${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
