name: Build and Deploy
permissions: {}
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deploy-artifacts:
    name: Deploy Artifacts
    needs: [ build, test ]
    uses: ./.github/workflows/deploy-artifacts.yml
    with:
      should-deploy-artifacts: ${{ needs.build.outputs.should-deploy-artifacts }}
    secrets: inherit
  publish-plugins:
    name: Publish Plugins
    needs: [ deploy-artifacts ]
    uses: ./.github/workflows/publish-plugins.yml
    with:
      should-publish-plugins: ${{ needs.deploy-artifacts.outputs.artifacts-deployed }}
      project-version: ${{ needs.deploy-artifacts.outputs.project-version }}
    secrets: inherit
  send-notification:
    name: Send Notification
    needs: [ publish-plugins ]
    if: ${{ failure() || cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: spring-io/spring-security-release-tools/.github/actions/send-notification@v1
        with:
          webhook-url: ${{ secrets.SPRING_SECURITY_CI_GCHAT_WEBHOOK_URL }}
