name: Dependabot - Auto-merge PR

on:
  pull_request:
    branches:
      - main
      - '*.x'
      - 'docs-build'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@0b29122fc5dacb27ad714f64888cd8408295f2f7 # main
    with:
      mergeArguments: --auto --rebase
