name: Deploy Artifacts
permissions: {}
on:
  workflow_call:
    inputs:
      runs-on:
        description: GitHub Actions runner to run the deploy task on.
        required: false
        default: 'ubuntu-latest'
        type: string
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false
      ARTIFACTORY_USERNAME:
        required: false
      ARTIFACTORY_PASSWORD:
        required: false
      COMMERCIAL_ARTIFACTORY_USERNAME:
        required: false
      COMMERCIAL_ARTIFACTORY_PASSWORD:
        required: false
      CENTRAL_TOKEN_USERNAME:
        required: false
      CENTRAL_TOKEN_PASSWORD:
        required: false
      GPG_PRIVATE_KEY:
        required: false
      GPG_PASSPHRASE:
        required: false

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  ARTIFACTORY_USERNAME: ${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME || secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD || secrets.ARTIFACTORY_PASSWORD }}

jobs:
  deploy-artifacts:
    name: Deploy Artifacts
    runs-on: ${{ inputs.runs-on }}
    outputs:
      project-version: ${{ steps.project-version.outputs.version }}
      project-snapshot: ${{ steps.project-version.outputs.snapshot }}
    steps:
      - name: Download local Maven repository
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
        with:
          name: local-maven-repository
          path: local-maven-repository
      - id: project-version
        name: Extract Project Version
        uses: spring-io/spring-release-actions/compute-version@708379dd0580adcd6dddf4e3754c8accec4801d4
        with:
          artifact-path: local-maven-repository/org/springframework/security/spring-security-core
      - id: deploy-location
        name: Compute Deploy Location
        uses: spring-io/spring-release-actions/compute-artifact-repository@708379dd0580adcd6dddf4e3754c8accec4801d4
        with:
          version: ${{ steps.project-version.outputs.version }}
      - name: Deploy Artifacts
        uses: spring-io/spring-security-actions/ensure-artifacts@0536cabc33626611bc907d4d3dc9fae3444bc859
        with:
          version: ${{ steps.project-version.outputs.version }}
          username: ${{ steps.deploy-location.outputs.name == 'maven2' && secrets.CENTRAL_TOKEN_USERNAME || secrets.ARTIFACTORY_USERNAME }}
          password: ${{ steps.deploy-location.outputs.name == 'maven2' && secrets.CENTRAL_TOKEN_PASSWORD || secrets.ARTIFACTORY_PASSWORD }}
          repository-uri: ${{ steps.deploy-location.outputs.uri }}
          repository-name: ${{ steps.deploy-location.outputs.name }}
          local-repository: local-maven-repository
          artifact-path: org/springframework/security/spring-security-core