name: Ensure Artifacts
permissions: {}
on:
  workflow_call:
    inputs:
      should-deploy-artifacts:
        description: Whether artifacts should be deployed.
        required: true
        type: string
      artifact-path:
        description: The artifact path within the repository (e.g. org/springframework/security/spring-security-core) used to skip deployment when the version is already present.
        required: true
        type: string
      runs-on:
        description: GitHub Actions runner to run the deploy task on.
        required: false
        default: 'ubuntu-latest'
        type: string
    outputs:
      artifacts-deployed:
        description: Whether artifacts were actually deployed.
        value: ${{ jobs.ensure-artifacts.outputs.artifacts-deployed }}
      project-version:
        description: The project version extracted from the current branch/tag.
        value: ${{ jobs.ensure-artifacts.outputs.project-version }}
    secrets:
      ARTIFACTORY_USERNAME:
        required: false
      ARTIFACTORY_PASSWORD:
        required: false
      COMMERCIAL_ARTIFACTORY_USERNAME:
        required: false
      COMMERCIAL_ARTIFACTORY_PASSWORD:
        required: false
      CENTRAL_TOKEN_USERNAME:
        required: false
      CENTRAL_TOKEN_PASSWORD:
        required: false

jobs:
  ensure-artifacts:
    name: Ensure Artifacts
    if: ${{ inputs.should-deploy-artifacts != 'false' }}
    runs-on: ${{ inputs.runs-on }}
    outputs:
      artifacts-deployed: ${{ steps.artifacts-deployed.outputs.result }}
      project-version: ${{ steps.project-version.outputs.version }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Download Local Maven Repository
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: local-maven-repository
          path: build/publications/repos
      - id: project-version
        name: Extract Project Version
        uses: spring-io/spring-release-actions/compute-version@a1f321783a0769dd2aea4fad6c2ae2f95a52b885 # 0.0.5
      - id: deploy-location
        name: Compute Deploy Location
        uses: spring-io/spring-release-actions/compute-artifact-repository@a1f321783a0769dd2aea4fad6c2ae2f95a52b885 # 0.0.5
        with:
          version: ${{ steps.project-version.outputs.version }}
      - name: Ensure Artifacts
        uses: spring-io/spring-security-actions/ensure-artifacts@f8ef0d53fc61799c18f19bc6a4c42ccb9aa265de
        with:
          version: ${{ steps.project-version.outputs.version }}
          username: ${{ vars.COMMERCIAL == 'true' && secrets.COMMERCIAL_ARTIFACTORY_USERNAME || (steps.deploy-location.outputs.name == 'maven2' && secrets.CENTRAL_TOKEN_USERNAME || secrets.ARTIFACTORY_USERNAME) }}
          password: ${{ vars.COMMERCIAL == 'true' && secrets.COMMERCIAL_ARTIFACTORY_PASSWORD || (steps.deploy-location.outputs.name == 'maven2' && secrets.CENTRAL_TOKEN_PASSWORD || secrets.ARTIFACTORY_PASSWORD) }}
          repository-uri: ${{ steps.deploy-location.outputs.uri }}
          repository-name: ${{ steps.deploy-location.outputs.name }}
          project: ${{ steps.deploy-location.outputs.project }}
          artifact-path: ${{ inputs.artifact-path }}
          local-repository: build/publications/repos
      - id: artifacts-deployed
        name: Artifacts Deployed
        run: echo "result=true" >> $GITHUB_OUTPUT
