name: Stage Release Announcements

on:
  workflow_call:
    inputs:
      version:
        description: The project version to stage
        required: true
        type: string
      branch:
        description: The branch to release from. Defaults to deriving it from version (e.g. 1.2.3 -> 1.2.x).
        required: false
        type: string
    secrets:
      GH_ACTIONS_REPO_TOKEN:
        required: true

jobs:
  stage-release-announcements:
    name: Stage Release Announcements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'
      - id: branch-name
        name: Extract Branch Name
        env:
          VERSION: ${{ inputs.version }}
          BRANCH: ${{ inputs.branch }}
        run: echo "branch=${BRANCH:-${VERSION%.*}.x}" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        env:
          TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
          BRANCH: ${{ steps.branch-name.outputs.branch }}
          VERSION: ${{ inputs.version }}
        run: ./gradlew createGitHubRelease -PnextVersion=$VERSION -Pbranch=$BRANCH -PcreateRelease=true -PgitHubAccessToken=$TOKEN
