# DEPRECATED: This workflow is deprecated in favor of release-announcements-stage.yml.
name: "Release - Publish Release Notes"

permissions:
  contents: write
  issues: write
  pull-requests: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The milestone/tag to generate and publish release notes for (for example, 6.3.1)"
        required: true

jobs:
  publish-release-notes:
    name: "Publish Release Notes"
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation Notice
        run: echo "::warning title=Deprecated Workflow::release-publish-release-notes.yml is deprecated; use release-announcements-stage.yml instead."
      - name: Publish Release Notes
        uses: spring-io/spring-security-actions/publish-release-notes@96df48300f5fa058d0765832d48a534cc6a378d5 # 0.0.3
        with:
          tag: ${{ inputs.version }}
          config-file: etc/release-notes-sections.yml
