name: Test
permissions: {}
on:
  workflow_call:
    inputs:
      java-version:
        description: Version of the JDK to use to run the Gradle command.
        required: false
        default: '17'
        type: string
      distribution:
        description: Distribution of the JDK to use to run the Gradle command.
        required: false
        default: 'temurin'
        type: string
      ref:
        description: The branch or tag to test
        required: false
        default: ${{ github.ref }}
        type: string
      test-args:
        description: Arguments for the gradle test command.
        required: false
        default: ''
        type: string
      runs-on:
        description: GitHub Actions runner to run the build task on.
        required: false
        default: 'ubuntu-latest'
        type: string
    secrets:
      ARTIFACTORY_USERNAME:
        required: false
      ARTIFACTORY_PASSWORD:
        required: false
      COMMERCIAL_ARTIFACTORY_USERNAME:
        required: false
      COMMERCIAL_ARTIFACTORY_PASSWORD:
        required: false
      DEVELOCITY_ACCESS_KEY:
        required: false

jobs:
  test:
    name: Test
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          repository: spring-io/spring-security-release-tools
          ref: ${{ github.action_ref }}
          path: _srt
          fetch-depth: 1
      - name: Run Tests of ${{ inputs.ref }}
        uses: ./_srt/.github/actions/run-gradle
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          gradle-args: test ${{ inputs.test-args }}
          init-script: ${{ vars.COMMERCIAL == 'true' && 'spring-enterprise' || 'spring-oss' }}
          artifactory-username: ${{ vars.COMMERCIAL == 'true' && secrets.COMMERCIAL_ARTIFACTORY_USERNAME || secrets.ARTIFACTORY_USERNAME }}
          artifactory-password: ${{ vars.COMMERCIAL == 'true' && secrets.COMMERCIAL_ARTIFACTORY_PASSWORD || secrets.ARTIFACTORY_PASSWORD }}
          develocity-access-key: ${{ vars.COMMERCIAL != 'true' && secrets.DEVELOCITY_ACCESS_KEY || '' }}
