name: Test
permissions: {}
on:
  workflow_call:
    inputs:
      java-version:
        description: Version of the JDK to use to run the Gradle command.
        required: false
        default: '17'
        type: string
      distribution:
        description: Distribution of the JDK to use to run the Gradle command.
        required: false
        default: 'temurin'
        type: string
      test-args:
        description: Arguments for the gradle test command.
        required: false
        default: ''
        type: string
      runs-on:
        description: GitHub Actions runner to run the build task on.
        required: false
        default: 'ubuntu-latest'
        type: string
    secrets:
      ARTIFACTORY_USERNAME:
        required: false
      ARTIFACTORY_PASSWORD:
        required: false
      COMMERCIAL_ARTIFACTORY_USERNAME:
        required: false
      COMMERCIAL_ARTIFACTORY_PASSWORD:
        required: false
      DEVELOCITY_ACCESS_KEY:
        required: false

jobs:
  test:
    name: Test
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: spring-io/spring-security-release-tools
          ref: ${{ github.action_ref }}
          path: _srt
          fetch-depth: 1
      - name: Set up JDK ${{ inputs.java-version }}
        uses: spring-io/spring-gradle-build-action@c8668747d7c264864c8c7f7026d0d277d14a78dc # v2.0.6
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
      - uses: ./_srt/.github/actions/run-gradle
        if: ${{ vars.COMMERCIAL == 'true' }}
        with:
          gradle-args: test ${{ inputs.test-args }}
          init-script: spring-enterprise
          artifactory-username: ${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}
          artifactory-password: ${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}
      - uses: ./_srt/.github/actions/run-gradle
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          gradle-args: test ${{ inputs.test-args }}
          init-script: ${{ vars.COMMERCIAL == 'true' && 'spring-enterprise' || 'spring-oss' }}
          artifactory-username: ${{ vars.COMMERCIAL == 'true' && secrets.COMMERCIAL_ARTIFACTORY_USERNAME || secrets.ARTIFACTORY_USERNAME }}
          artifactory-password: ${{ vars.COMMERCIAL == 'true' && secrets.COMMERCIAL_ARTIFACTORY_PASSWORD || secrets.ARTIFACTORY_PASSWORD }}
          develocity-access-key: ${{ vars.COMMERCIAL != 'true' && secrets.DEVELOCITY_ACCESS_KEY || '' }}
